--
-- PostgreSQL database dump
--

\restrict 9r88zDjgg9Fh0RQhV94a6drxpmCWDfeZWInzgJrY3UxbTFzQFxAJQycnmltdh73

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-05-18 00:23:21

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 21437)
-- Name: project_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_members (
    member_id bigint NOT NULL,
    project_id bigint NOT NULL
);


ALTER TABLE public.project_members OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 21445)
-- Name: projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects (
    color character varying(7),
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    description text,
    name character varying(255) NOT NULL,
    status character varying(255) DEFAULT 'INITIATED'::character varying,
    CONSTRAINT projects_status_check CHECK (((status)::text = ANY ((ARRAY['INITIATED'::character varying, 'PLANNING'::character varying, 'IN_PROGRESS'::character varying, 'ON_HOLD'::character varying, 'MONITORING'::character varying, 'COMPLETED'::character varying, 'CLOSED'::character varying])::text[])))
);


ALTER TABLE public.projects OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 21444)
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 29624)
-- Name: reminder_comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reminder_comments (
    id bigint NOT NULL,
    date timestamp(6) without time zone,
    text text,
    reminder_id bigint
);


ALTER TABLE public.reminder_comments OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 29623)
-- Name: reminder_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reminder_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reminder_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 29633)
-- Name: reminders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reminders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    due_date date,
    start_date date,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT reminders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'OVERDUE'::character varying])::text[])))
);


ALTER TABLE public.reminders OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 29632)
-- Name: reminders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reminders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reminders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 21454)
-- Name: task_assignees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_assignees (
    member_id bigint NOT NULL,
    task_id bigint NOT NULL
);


ALTER TABLE public.task_assignees OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 29610)
-- Name: task_comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_comments (
    id bigint NOT NULL,
    author character varying(255),
    date timestamp(6) without time zone,
    text text,
    task_id bigint
);


ALTER TABLE public.task_comments OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 29609)
-- Name: task_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 21460)
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks (
    due_date date,
    progress_actual integer,
    start_date date,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    parent_id bigint,
    project_id bigint,
    updated_at timestamp(6) without time zone,
    description text,
    priority character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT tasks_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT tasks_status_check CHECK (((status)::text = ANY ((ARRAY['TODO'::character varying, 'IN_PROGRESS'::character varying, 'IN_REVIEW'::character varying, 'DONE'::character varying, 'BLOCKED'::character varying])::text[])))
);


ALTER TABLE public.tasks OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 21459)
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 21474)
-- Name: team_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.team_members (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    role character varying(255)
);


ALTER TABLE public.team_members OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 21473)
-- Name: team_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.team_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5065 (class 0 OID 21437)
-- Dependencies: 219
-- Data for Name: project_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.project_members (member_id, project_id) FROM stdin;
\.


--
-- TOC entry 5067 (class 0 OID 21445)
-- Dependencies: 221
-- Data for Name: projects; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.projects (color, created_at, id, description, name, status) FROM stdin;
#2196f3	2026-05-11 20:53:27.579313	1	\N	BICE	IN_PROGRESS
#3f51b5	2026-05-11 20:53:42.024473	2	\N	ODS Entel	IN_PROGRESS
#f44336	2026-05-11 20:53:48.65078	3	\N	ODS Santander Chile	IN_PROGRESS
#f44336	2026-05-12 16:32:26.611539	5	\N	Santander Consumer	PLANNING
\.


--
-- TOC entry 5076 (class 0 OID 29624)
-- Dependencies: 230
-- Data for Name: reminder_comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reminder_comments (id, date, text, reminder_id) FROM stdin;
\.


--
-- TOC entry 5078 (class 0 OID 29633)
-- Dependencies: 232
-- Data for Name: reminders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reminders (id, created_at, description, due_date, start_date, status, title, updated_at) FROM stdin;
\.


--
-- TOC entry 5068 (class 0 OID 21454)
-- Dependencies: 222
-- Data for Name: task_assignees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_assignees (member_id, task_id) FROM stdin;
2	261
1	263
1	264
1	265
1	266
2	267
4	269
4	270
4	271
2	272
3	273
2	276
4	277
2	278
1	280
3	283
1	284
4	285
6	285
1	286
11	287
2	288
7	288
1	290
1	291
1	292
1	293
5	293
4	294
2	296
1	299
3	300
1	301
1	302
1	303
1	304
1	305
2	306
4	307
3	308
3	309
4	312
2	313
1	314
3	315
3	316
2	317
3	319
1	320
3	321
4	322
6	322
4	323
6	323
2	324
1	325
2	327
3	328
2	329
3	329
3	330
1	331
1	333
3	334
2	335
4	275
6	275
2	311
7	262
3	298
1	336
1	274
1	279
5	310
11	289
2	318
\.


--
-- TOC entry 5074 (class 0 OID 29610)
-- Dependencies: 228
-- Data for Name: task_comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_comments (id, author, date, text, task_id) FROM stdin;
11	Tú	2026-05-14 19:05:56.614	Se queda detenido mañana, por que falabella no ha mandado los datos de integración, estamos avando en base a dummy.	310
12	Tú	2026-05-14 19:06:42.215	Falabella va mandar los datos la proxiama semana no dió fecha	310
13	Tú	2026-05-14 22:07:54.64	Se envía MR a arquitectura para la vista de los reportes	318
\.


--
-- TOC entry 5070 (class 0 OID 21460)
-- Dependencies: 224
-- Data for Name: tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks (due_date, progress_actual, start_date, created_at, id, parent_id, project_id, updated_at, description, priority, status, title) FROM stdin;
2026-05-22	50	2026-05-04	2026-05-12 22:56:21.376607	273	\N	2	2026-05-12 22:56:21.376607	\N	MEDIUM	BLOCKED	Reporte de Traza
2026-04-07	100	2026-03-03	2026-05-12 22:56:21.417606	283	\N	2	2026-05-12 22:56:21.417606	\N	MEDIUM	DONE	Multiconvenio
2026-07-07	55	2026-05-18	2026-05-12 22:56:21.421605	284	\N	2	2026-05-12 22:56:21.421605	\N	HIGH	IN_PROGRESS	Migración/Configuración
2026-06-17	4	2026-05-05	2026-05-12 22:56:21.426605	285	\N	3	2026-05-12 22:56:21.426605	\N	MEDIUM	IN_PROGRESS	Desarrollo y Pruebas
2026-05-30	50	2026-05-04	2026-05-12 22:56:21.436606	287	\N	5	2026-05-12 22:56:21.436606	\N	LOW	IN_REVIEW	Discovery
2026-05-15	25	2026-05-04	2026-05-12 22:56:21.440607	288	\N	2	2026-05-12 22:56:21.440607	\N	MEDIUM	IN_PROGRESS	Documentación
2026-05-15	98	2026-03-05	2026-05-12 22:56:21.459606	293	\N	2	2026-05-12 22:56:21.459606	\N	MEDIUM	IN_PROGRESS	Integración
2026-05-05	100	2026-04-27	2026-05-12 22:56:21.463607	294	\N	3	2026-05-12 22:56:21.463607	\N	MEDIUM	DONE	Analisis y Diseño Técnico
2026-04-23	100	2026-04-20	2026-05-12 22:56:21.510605	307	\N	3	2026-05-12 22:56:21.510605	\N	MEDIUM	DONE	Kick Off
2026-06-22	29	2026-05-07	2026-05-12 22:56:21.53375	314	\N	1	2026-05-12 22:56:21.53375	\N	MEDIUM	IN_PROGRESS	Integración boton Scotiabank
2026-05-13	100	2026-05-12	2026-05-12 22:56:21.443606	289	285	3	2026-05-14 16:33:57.472986	\N	MEDIUM	DONE	Conectividad Comercios -EVTC
2026-06-15	90	2026-06-09	2026-05-12 22:56:21.493607	302	284	2	2026-05-14 12:00:27.703321	\N	MEDIUM	TODO	Migración/Configuración Webpay PU y One Click
2026-05-08	100	2026-05-07	2026-05-12 22:56:21.330822	264	314	1	2026-05-12 22:56:21.626267	\N	MEDIUM	DONE	Discovery
2026-04-30	100	2026-04-17	2026-05-12 22:56:21.335606	265	293	2	2026-05-12 22:56:21.628268	\N	MEDIUM	DONE	Desarrollo integración botones Servipag
2026-05-15	100	2026-05-04	2026-05-12 22:56:21.341607	266	293	2	2026-05-12 22:56:21.631268	\N	MEDIUM	DONE	Desarrollo integración botones Mercado Pago
2026-07-07	30	2026-07-01	2026-05-12 22:56:21.405606	280	284	2	2026-05-14 12:00:15.245037	\N	MEDIUM	TODO	Migración/Configuración Compraqui Ventas y Mercado Pago
2026-06-17	0	2026-06-08	2026-05-12 22:56:21.357606	269	285	3	2026-05-12 22:56:21.639266	\N	MEDIUM	TODO	Conectividad Comercios -EVTC
2026-05-05	100	2026-04-27	2026-05-12 22:56:21.362606	270	294	3	2026-05-12 22:56:21.641267	\N	MEDIUM	DONE	Diseño Técnico y Plan de Pruebas
2026-04-20	100	2026-04-20	2026-05-12 22:56:21.367606	271	307	3	2026-05-12 22:56:21.644268	\N	MEDIUM	DONE	Discovery
2026-04-07	100	2026-03-01	2026-05-12 22:56:21.372607	272	329	2	2026-05-12 22:56:21.647268	\N	MEDIUM	DONE	Parte 1 NRP_012 Contabilizaci¢n manual de dep¢sitos_v1.0.docx
2026-09-05	90	2026-05-12	2026-05-12 22:56:21.477606	298	321	2	2026-05-14 12:01:01.98182	\N	MEDIUM	IN_REVIEW	Aplicar balanceo Frontend y Backend
2026-04-07	90	2026-03-02	2026-05-12 22:56:21.548268	318	335	2	2026-05-14 18:07:56.693281	\N	CRITICAL	BLOCKED	Parte 2 NRP_010 Reporte de Ventas_v1.0.docx
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.389607	276	329	2	2026-05-12 22:56:21.653268	\N	MEDIUM	DONE	Parte 1 NRS_100 Recibir notificaci¢n de pago desde canal_v1.0.docx
2026-06-09	0	2026-06-08	2026-05-12 22:56:21.393606	277	285	3	2026-05-12 22:56:21.655268	\N	MEDIUM	TODO	Solicitar Certificación (Generar SCI)
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.398607	278	329	2	2026-05-12 22:56:21.657269	\N	MEDIUM	DONE	Parte 1 NRS_091 Regenerar rendiciones de pagos a empresas v1.1.docx
2026-05-18	0	2026-05-14	2026-05-12 22:56:21.496605	303	314	1	2026-05-14 13:40:08.703458	\N	MEDIUM	IN_PROGRESS	RSIS003 - Redirigir al usuario al comercio
2026-06-30	50	2026-06-23	2026-05-12 22:56:21.431605	286	284	2	2026-05-14 12:00:21.064524	\N	HIGH	TODO	Migración/Configuración Webpay Ventas y Link de Pago
2026-06-22	30	2026-06-16	2026-05-12 22:56:21.323821	263	284	2	2026-05-14 12:00:24.992776	\N	MEDIUM	TODO	Migración/Configuración Servipag y Falabella
2026-06-03	31	2026-05-05	2026-05-12 22:56:21.385606	275	285	3	2026-05-14 09:43:31.754891	\N	MEDIUM	IN_PROGRESS	Desarrollo + Pruebas unitarias
2026-04-09	100	2026-03-26	2026-05-12 22:56:21.451606	291	293	2	2026-05-12 22:56:21.670268	\N	MEDIUM	DONE	Desarrollo integración botones Banco Scotiabank
2026-05-19	0	2026-05-18	2026-05-12 22:56:21.455606	292	314	1	2026-05-12 22:56:21.672268	\N	MEDIUM	TODO	RSIS004 - Conciliar y Rendir los pagos del botón Scotiabank
2026-05-22	27	2026-05-11	2026-05-12 22:56:21.31882	262	288	2	2026-05-14 11:13:21.406504	\N	MEDIUM	IN_PROGRESS	Actualizar manual CRT
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.470606	296	335	2	2026-05-12 22:56:21.676268	\N	MEDIUM	DONE	Parte 2 NRP_011 Reporte de pago unificadov1.0.docx
2026-05-14	100	2026-05-12	2026-05-12 22:56:21.401605	279	314	1	2026-05-14 13:39:58.998595	\N	MEDIUM	IN_PROGRESS	RSIS002 - Procesar respuesta de pago desde botón
2026-05-22	82	2026-05-04	2026-05-12 22:56:21.519611	310	293	2	2026-05-14 16:04:51.793664	\N	MEDIUM	IN_PROGRESS	Desarrollo integración botones Falabella
2026-03-18	100	2026-03-05	2026-05-12 22:56:21.481606	299	293	2	2026-05-12 22:56:21.681269	\N	MEDIUM	DONE	Desarrollo integración botones Bco Santander
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.48461	300	329	2	2026-05-12 22:56:21.682269	\N	MEDIUM	DONE	Parte 1 NRS_015 Reversa por rechazo parcial V1.0.docx
2026-06-22	0	2026-06-20	2026-05-12 22:56:21.488606	301	314	1	2026-05-12 22:56:21.684267	\N	MEDIUM	TODO	Solicitar Certificación (Generar SCI)
2026-05-25	95	2026-05-18	2026-05-12 22:56:21.380607	274	284	2	2026-05-14 16:04:26.911728	\N	MEDIUM	TODO	Migración/Configuración Santander y BCH
2026-04-01	100	2026-03-19	2026-05-12 22:56:21.504605	305	293	2	2026-05-12 22:56:21.690267	\N	MEDIUM	DONE	Desarrollo integración botones BCI ON US
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.507606	306	335	2	2026-05-12 22:56:21.692268	\N	MEDIUM	DONE	Parte 2 NRP_008 Reporte de Novedades Clave v1.0.docx
2026-04-07	100	2026-03-03	2026-05-12 22:56:21.513607	308	283	2	2026-05-12 22:56:21.694268	\N	MEDIUM	DONE	Deuda técnica NRS_047 Permitir Configuración Reglas de Pago Multiconvenio
2026-05-22	50	2026-05-04	2026-05-12 22:56:21.516606	309	273	2	2026-05-12 22:56:21.695269	\N	MEDIUM	BLOCKED	Mejora y optimiación del reporte de traza (Front, Back y BD)
2026-05-22	27	2026-05-11	2026-05-12 22:56:21.523611	311	288	2	2026-05-14 11:13:15.492048	\N	MEDIUM	IN_PROGRESS	Actualizar Manual Operaciones
2026-04-23	100	2026-04-22	2026-05-12 22:56:21.526612	312	307	3	2026-05-12 22:56:21.700268	\N	MEDIUM	DONE	Habilitación de accesos
2026-04-07	100	2026-03-01	2026-05-12 22:56:21.530611	313	329	2	2026-05-12 22:56:21.702268	\N	MEDIUM	DONE	Parte 1 NR_002 Notificar pago a Entel TMF_v1.0.docx
2026-05-07	100	2026-05-04	2026-05-12 22:56:21.536947	315	309	2	2026-05-12 22:56:21.703267	\N	MEDIUM	DONE	Diseño Técnico
2026-05-22	0	2026-05-13	2026-05-12 22:56:21.541139	316	309	2	2026-05-12 22:56:21.705268	\N	MEDIUM	BLOCKED	Desarrollo y pruebas
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.544268	317	329	2	2026-05-12 22:56:21.706268	\N	MEDIUM	DONE	Parte 1 NRS_101 Notificar pago a empresa_v1.0.docx
2026-09-05	40	2026-05-12	2026-05-12 22:56:21.558268	321	\N	2	2026-05-12 22:56:21.558268	\N	MEDIUM	IN_REVIEW	Desarrollo General
2026-04-07	100	2026-03-01	2026-05-12 22:56:21.589269	329	\N	2	2026-05-12 22:56:21.589269	\N	MEDIUM	DONE	Parte 1 - RSIS
2026-04-07	98	2026-03-02	2026-05-12 22:56:21.609268	335	\N	2	2026-05-12 22:56:21.609268	\N	CRITICAL	BLOCKED	Parte 2 - Reportería
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.269038	261	329	2	2026-05-12 22:56:21.613269	\N	MEDIUM	DONE	Parte 1 NRS_029 Conciliaci¢n Web_v1.0.docx
2026-04-07	100	2026-03-01	2026-05-12 22:56:21.347611	267	329	2	2026-05-12 22:56:21.634268	\N	MEDIUM	DONE	Parte 1 NRP_013  Consulta clave de conciliaci¢n v1.0 .docx
2026-05-12	100	2026-05-08	2026-05-12 22:56:21.448607	290	314	1	2026-05-12 22:56:21.668268	\N	MEDIUM	DONE	RSIS001 - Agrega Botón de Pago Banco Scotiabank
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.551269	319	329	2	2026-05-12 22:56:21.709267	\N	MEDIUM	DONE	Parte 1 NRS_103 Administrar reglas de aplicaci¢n de reversas_v1.1.docx
2026-04-16	100	2026-04-02	2026-05-12 22:56:21.555268	320	293	2	2026-05-12 22:56:21.711266	\N	MEDIUM	DONE	Desarrollo integración botones MATCH
2026-06-04	0	2026-06-03	2026-05-12 22:56:21.562267	322	285	3	2026-05-12 22:56:21.712268	\N	MEDIUM	TODO	Manual SCI
2026-06-08	0	2026-06-03	2026-05-12 22:56:21.567268	323	285	3	2026-05-12 22:56:21.713269	\N	MEDIUM	TODO	Pruebas de Integración
2026-04-07	100	2026-03-01	2026-05-12 22:56:21.572267	324	329	2	2026-05-12 22:56:21.715269	\N	MEDIUM	DONE	Parte 1 NRP_015 Cartola historica de pagos1.0.docx
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.582269	327	335	2	2026-05-12 22:56:21.721268	\N	MEDIUM	DONE	Parte 2 NRP_014 Reporte de transacciones por fecha contable V1.0.docx
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.586268	328	329	2	2026-05-12 22:56:21.722268	\N	MEDIUM	DONE	Parte 1 NRS_087 Enviar reversa a empresa_v1.0.docx
2026-04-07	100	2026-03-02	2026-05-12 22:56:21.593268	330	329	2	2026-05-12 22:56:21.723267	\N	MEDIUM	DONE	Parte 1 NRS_085 Recibir reversa desde canal_v1.0.docx
2026-05-22	0	2026-05-19	2026-05-12 22:56:21.596269	331	314	1	2026-05-12 22:56:21.724271	\N	MEDIUM	TODO	RSIS005 - Habilitar botón BANCO SCOTIABANK en el Dashboard de BICE
2026-04-23	100	2026-04-10	2026-05-12 22:56:21.602269	333	293	2	2026-05-12 22:56:21.725268	\N	MEDIUM	DONE	Desarrollo integración botones OneCLick
2026-04-07	100	2026-03-03	2026-05-12 22:56:21.606268	334	283	2	2026-05-12 22:56:21.726268	\N	MEDIUM	DONE	Deuda técnica NRS_046 MultiConvenio Webpay Mall
2026-06-08	50	2026-06-02	2026-05-12 22:56:21.500605	304	284	2	2026-05-14 12:00:30.626428	\N	MEDIUM	TODO	Migración/Configuración Scotiabank y Compraqui PU
2026-06-01	40	2026-05-26	2026-05-12 22:56:21.575268	325	284	2	2026-05-14 12:00:33.162396	\N	MEDIUM	TODO	Migración/Configuración BCI, MACH y BCI OnUs
2026-05-20	20	2026-05-15	2026-05-14 11:09:26.584382	336	293	2	2026-05-14 12:01:20.329	\N	MEDIUM	IN_PROGRESS	Conciliación de Falabella
\.


--
-- TOC entry 5072 (class 0 OID 21474)
-- Dependencies: 226
-- Data for Name: team_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.team_members (created_at, id, email, name, role) FROM stdin;
2026-05-11 20:54:26.950977	1	test1@test.com	Rodrigo Dominguez	Desarrollador Senior
2026-05-11 20:54:45.705525	2	test2@test.com	Pablo Villanea	Desarrollador
2026-05-11 20:55:45.439414	4	test4@test.com	Yan Santibañez	Desarrollador Senior
2026-05-11 20:56:02.858432	5	test5@test.com	Camilo Torres	Desarrollador Senior
2026-05-11 20:56:57.115227	6	test6@test.com	Christian Aguilar	Desarrollador
2026-05-11 23:33:26.778797	7	test7@test.com	Mauricio Aguila	Desarrollador
2026-05-12 12:02:58.199418	8	test8@test.com	Juan Vegas	Desarrollador
2026-05-12 12:03:20.287661	9	test9@test.com	Sergio Mansilla	Desarrollador Senior
2026-05-12 12:10:22.625693	10	test10@test.com	Veronica Melo	QA
2026-05-12 16:32:55.537282	11	test11@test.com	Sergio Fica	Líder Técnico
2026-05-11 20:55:07.71821	3	test3@test.com	Anibal Toro	Desarrollador Senior
\.


--
-- TOC entry 5084 (class 0 OID 0)
-- Dependencies: 220
-- Name: projects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.projects_id_seq', 5, true);


--
-- TOC entry 5085 (class 0 OID 0)
-- Dependencies: 229
-- Name: reminder_comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reminder_comments_id_seq', 1, false);


--
-- TOC entry 5086 (class 0 OID 0)
-- Dependencies: 231
-- Name: reminders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reminders_id_seq', 1, false);


--
-- TOC entry 5087 (class 0 OID 0)
-- Dependencies: 227
-- Name: task_comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_comments_id_seq', 13, true);


--
-- TOC entry 5088 (class 0 OID 0)
-- Dependencies: 223
-- Name: tasks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_id_seq', 336, true);


--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 225
-- Name: team_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.team_members_id_seq', 11, true);


--
-- TOC entry 4895 (class 2606 OID 21443)
-- Name: project_members project_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_pkey PRIMARY KEY (member_id, project_id);


--
-- TOC entry 4897 (class 2606 OID 21453)
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 29631)
-- Name: reminder_comments reminder_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reminder_comments
    ADD CONSTRAINT reminder_comments_pkey PRIMARY KEY (id);


--
-- TOC entry 4909 (class 2606 OID 29643)
-- Name: reminders reminders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reminders
    ADD CONSTRAINT reminders_pkey PRIMARY KEY (id);


--
-- TOC entry 4905 (class 2606 OID 29617)
-- Name: task_comments task_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_comments
    ADD CONSTRAINT task_comments_pkey PRIMARY KEY (id);


--
-- TOC entry 4899 (class 2606 OID 21472)
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- TOC entry 4901 (class 2606 OID 21485)
-- Name: team_members team_members_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT team_members_email_key UNIQUE (email);


--
-- TOC entry 4903 (class 2606 OID 21483)
-- Name: team_members team_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT team_members_pkey PRIMARY KEY (id);


--
-- TOC entry 4912 (class 2606 OID 21496)
-- Name: task_assignees fk930f4qf8b81ppo2go62xnwuj4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_assignees
    ADD CONSTRAINT fk930f4qf8b81ppo2go62xnwuj4 FOREIGN KEY (member_id) REFERENCES public.team_members(id);


--
-- TOC entry 4916 (class 2606 OID 29618)
-- Name: task_comments fk9517viwn2geh1gpivj6l9y64u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_comments
    ADD CONSTRAINT fk9517viwn2geh1gpivj6l9y64u FOREIGN KEY (task_id) REFERENCES public.tasks(id);


--
-- TOC entry 4910 (class 2606 OID 21491)
-- Name: project_members fkdki1sp2homqsdcvqm9yrix31g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT fkdki1sp2homqsdcvqm9yrix31g FOREIGN KEY (project_id) REFERENCES public.projects(id);


--
-- TOC entry 4914 (class 2606 OID 21506)
-- Name: tasks fkmhda52toac2weso6474wmldtn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fkmhda52toac2weso6474wmldtn FOREIGN KEY (parent_id) REFERENCES public.tasks(id);


--
-- TOC entry 4917 (class 2606 OID 29644)
-- Name: reminder_comments fknx99ou4c6bv0agv004mcxdbx7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reminder_comments
    ADD CONSTRAINT fknx99ou4c6bv0agv004mcxdbx7 FOREIGN KEY (reminder_id) REFERENCES public.reminders(id);


--
-- TOC entry 4913 (class 2606 OID 21501)
-- Name: task_assignees fks0jy5sv972lpa2wfx95m7xebb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_assignees
    ADD CONSTRAINT fks0jy5sv972lpa2wfx95m7xebb FOREIGN KEY (task_id) REFERENCES public.tasks(id);


--
-- TOC entry 4911 (class 2606 OID 21486)
-- Name: project_members fkscl3xr15knlxslevpfwsi8i83; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT fkscl3xr15knlxslevpfwsi8i83 FOREIGN KEY (member_id) REFERENCES public.team_members(id);


--
-- TOC entry 4915 (class 2606 OID 21511)
-- Name: tasks fksfhn82y57i3k9uxww1s007acc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fksfhn82y57i3k9uxww1s007acc FOREIGN KEY (project_id) REFERENCES public.projects(id);


-- Completed on 2026-05-18 00:23:21

--
-- PostgreSQL database dump complete
--

\unrestrict 9r88zDjgg9Fh0RQhV94a6drxpmCWDfeZWInzgJrY3UxbTFzQFxAJQycnmltdh73

