spring.application.name=task-tracker-backend
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/task_tracker
spring.datasource.username=postgres
spring.datasource.password=local1234$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Seed data solo cuando la tabla est? vac?a
spring.sql.init.mode=never
